In [4]:
import pandas as pd

In [6]:
df1= pd.read_csv('/Users/Gargi Shukla/Documents/My Python Repository/Dataset/US States Data/state-population.csv')
df2= pd.read_csv('/Users/Gargi Shukla/Documents/My Python Repository/Dataset/US States Data/state-areas.csv')
df3= pd.read_csv('/Users/Gargi Shukla/Documents/My Python Repository/Dataset/US States Data/state-abbrevs.csv')

In [8]:
df1.head()

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [9]:
df2.head()

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [10]:
df3.head()

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [ ]:
df_merge=pd.merge(
            pd.merge(df1,df3,how='left',left_on='state/region',right_on='abbreviation'),
                df2,how='left',left_on='state',right_on='state')

In [20]:
df_merge

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
0,AL,under18,2012,1117489.0,Alabama,AL,52423.0
1,AL,total,2012,4817528.0,Alabama,AL,52423.0
2,AL,under18,2010,1130966.0,Alabama,AL,52423.0
3,AL,total,2010,4785570.0,Alabama,AL,52423.0
4,AL,under18,2011,1125763.0,Alabama,AL,52423.0
...,...,...,...,...,...,...,...
2539,USA,total,2010,309326295.0,NaN,NaN,NaN
2540,USA,under18,2011,73902222.0,NaN,NaN,NaN
2541,USA,total,2011,311582564.0,NaN,NaN,NaN
2542,USA,under18,2012,73708179.0,NaN,NaN,NaN
2543,USA,total,2012,313873685.0,NaN,NaN,NaN

In [28]:
df_merge.drop(columns='abbreviation',inplace=True)

In [29]:
df_merge.isnull().sum()

state/region      0
ages              0
year              0
population       20
state            96
area (sq. mi)    96
dtype: int64

In [30]:
(df_merge.isnull().sum()/len(df_merge))*100

state/region     0.000000
ages             0.000000
year             0.000000
population       0.786164
state            3.773585
area (sq. mi)    3.773585
dtype: float64